#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Setting up Git repository for Render backend...${NC}"

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo -e "${RED}❌ Error: package.json not found!${NC}"
    echo "Please run this script from your render-backend directory"
    exit 1
fi

# Initialize git
echo -e "${BLUE}📁 Initializing git repository...${NC}"
git init

# Create .gitignore
echo -e "${BLUE}📝 Creating .gitignore...${NC}"
cat > .gitignore << 'EOF'
# Dependencies
node_modules/
package-lock.json

# Environment variables
.env
.env.local
.env.production

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output/

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt/

# Bower dependency directory (https://bower.io/)
bower_components/

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test
.env.production

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build output
.nuxt
dist

# Gatsby files
.cache/
public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
EOF

# Add all files
echo -e "${BLUE}📦 Adding files to git...${NC}"
git add .

# Initial commit
echo -e "${BLUE}💾 Creating initial commit...${NC}"
git commit -m "Initial commit: Render backend for Razorpay webhooks"

# Ask for GitHub repository name
echo -e "${BLUE}🔗 Enter your GitHub repository name (e.g., render-payment-webhook):${NC}"
read REPO_NAME

if [ -z "$REPO_NAME" ]; then
    REPO_NAME="render-payment-webhook"
    echo -e "${BLUE}Using default: $REPO_NAME${NC}"
fi

# Ask for GitHub username
echo -e "${BLUE}👤 Enter your GitHub username:${NC}"
read GITHUB_USERNAME

if [ -z "$GITHUB_USERNAME" ]; then
    GITHUB_USERNAME="manuraj7070"
    echo -e "${BLUE}Using default: $GITHUB_USERNAME${NC}"
fi

# Add remote
echo -e "${BLUE}🌍 Adding remote origin...${NC}"
git remote add origin "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"

echo -e "${GREEN}✅ Git repository initialized successfully!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "1. Create a new repository on GitHub: https://github.com/new"
echo -e "   Repository name: ${GREEN}$REPO_NAME${NC}"
echo -e "2. Run the following command to push:"
echo -e "   ${GREEN}git push -u origin main${NC}"
echo ""
echo -e "${BLUE}Or use this one-liner to push now:${NC}"
echo -e "${GREEN}git push -u origin main${NC}"